name: print_bluetooth_thermal_example
description: Demonstrates how to use the print_bluetooth_thermal plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  esc_pos_utils_plus: ^2.0.1+3
  #url_launcher: ^6.1.10
  #image: ^3.0.2
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^10.5.0

  geolocator: ^9.0.2
  workmanager: ^0.5.1
  blue_thermal_printer: ^1.2.3
  flutter_barcode_scanner: ^2.0.0
  dart_jsonwebtoken: ^2.8.2
  path_provider: ^2.0.14
  url_launcher: ^6.1.10
  http: ^0.13.5
  flutter_speed_dial: ^7.0.0
  get: ^4.6.5
  uuid: ^3.0.7
  sse: ^4.1.2
  connectivity_plus: ^4.0.1
  flutter_client_sse: ^1.0.0
  quiver: ^3.0.0
  permission_handler: ^10.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^0.20.1
  another_flushbar: ^1.12.30
  local_auth: ^2.1.6
  fl_chart: ^0.63.0
  qr_flutter: ^4.1.0
  shake: ^2.2.0

  flutter_local_notifications: ^15.1.0+1


  install_plugin: ^2.1.0
  fluttertoast: ^8.2.2
  dio: ^5.3.2
  file_picker: ^5.3.3
  print_bluetooth_thermal: ^1.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
